version: "3.9"

services:
  db_agenda:
    container_name: db_agenda
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 102030
      MYSQL_USER: root
      MYSQL_DATABASE: db_agenda
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata: {}
